In [6]:
#Write a Python program to convert an array to an ordinary list with the same items.
import numpy as np
a = np.array([1,2,3,4,5])
print(a.tolist())

[1, 2, 3, 4, 5]


In [34]:
#Write a NumPy program to compute the sum of the diagonal elements of a given array.
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
de = np.trace(a)
print(de)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [37]:
#Given an array of your choice, get all the values higher than X :
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
x = 4
c = []
for i in np.nditer(a):
    if i > x:
        c.append(i)
x = np.array(c)
print(x)

[5 6]


In [32]:
#Given two arrays, A & B have the same shape. 
#The task is to apply addition by hand: C is the new array. 
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.add(a,b)
print(c)

[[ 8 10 12]
 [14 16 18]]


In [7]:
#Write a NumPy program to subtract the mean of each row of a given matrix.

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.mean(a[0,:])
print(b)
c = np.mean(a[1,:])
print(c)
d= np.mean(a[2,:])
print(d)
e = b - c - d
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.0
5.0
8.0
-11.0
